
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configuraciones-globales-kubernetes
data:
    KAFKA_NODE_ID: "1"
    KAFKA_PROCESS_ROLES: "broker,controller"
    KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

    KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"


    KAFKA_LISTENERS: "INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093"
    KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092,EXTERNAL://localhost:9094"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
    KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

   #Autocreacion y limitacion de memoria
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    KAFKA_NUM_PARTITIONS: "1"
    KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"

    #Orquestador
    SERVER_PORT: "8080"
    SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
