apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventarios
  template:
    metadata:
      labels:
        app: inventarios
    spec:
      containers:
      - name: inventarios
        image: inventarios:0.0.2 
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: orquestador-secret
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: orquestador-secret
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orquestador-secret
              key: SPRING_DATASOURCE_PASSWORD
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-configuraciones-globales-kubernetes
              key: SERVER_PORT
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-configuraciones-globales-kubernetes
              key: SPRING_KAFKA_BOOTSTRAP_SERVERS
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"

---
apiVersion: v1
kind: Service
metadata:
  name: orquestador-service
spec:
  type: ClusterIP  # ⬅️ SOLO CLUSTER - NO EXPUESTO
  selector:
    app: orquestador
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081