apiVersion: v1
kind: Secret ## TIPO DE CONFIGURACION DE LO QUE SE TRATA EL ARCHIVO
metadata:
  name: Kafka-secrets
type: Opaque
data:        # derianmolina@gmail.com
      SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL215c3FsOjMzMDYvc3RhdHVzX29wZXJhdGlvbj91c2VTU0w9ZmFsc2Umc2VydmVyVGltZXpvbmU9VVRDJmFsbG93UHVibGljS2V5UmV0cmlldmFsPXRydWU= #jdbc:mysql://mysql:3306/status_operation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ZGVyaWFu
      SPRING_DATASOURCE_PASSWORD: ZGVyaWFu
     